### PR TITLE
Fix client checksum verification

### LINKED ISSUE #1232: Fix checksum check for zipped gov store proposals
Currently, the checksum is [verified](https://github.com/CosmWasm/wasmd/blob/v0.31.0-rc0/x/wasm/client/cli/gov_tx.go#L133) on the zipped wasm code on the client side. The server though uses the unzipped one.

There is a [patch](https://github.com/CosmWasm/wasmd/commit/5fd529419c9085ebb806a8839edb503317e998c1#diff-ce23d33d3468c256a60327a4043bde61e77bd83349e9d115f5e799313f427a3f) in the Osmosis fork but that one flips the scenario and does not work with unzipped wasm files

### PR DESCRIPTION
**Pull request by alpe**
Resolves #1232 

Support raw and gzipped source codes in CLI checksum verification. // fyi: @orkunkl

### CODE REVIEW

File: x/wasm/client/cli/tx_test.go [hunk 1]
```diff
@@ -57,3 +60,65 @@ func TestParseAccessConfigFlags(t *testing.T) {
...
+			},
+			expErr: true,
+		},
+	}
+	for name, spec := range specs {
+		t.Run(name, func(t *testing.T) {
+			flagSet := ProposalStoreCodeCmd().Flags()
+			require.NoError(t, flagSet.Parse(spec.args))
+
+			gotMsg, err := parseStoreCodeArgs("../../keeper/testdata/hackatom.wasm", mySender, flagSet)
```
Comment (pinosu) [inline x/wasm/client/cli/tx_test.go:109]:
```suggestion
			gotMsg, err := parseStoreCodeArgs(spec.srcPath, mySender, flagSet)
```

File: x/wasm/keeper/proposal_integration_test.go [hunk 2]
```diff
@@ -27,20 +27,31 @@ func TestStoreCodeProposal(t *testing.T) {
...
 	}{
 		"upload with pinning (default)": {
 			unpinCode: false,
+			code:      rawWasmCode,
 		},
 		"upload with code unpin": {
 			unpinCode: true,
+			code:      rawWasmCode,
+		},
+		"upload with raw wasm code": {
```
Comment (pinosu) [inline x/wasm/keeper/proposal_integration_test.go:50]: 👍

**Review by pinosu — APPROVED** [review]
Good work and nice set of tests. 
Please fix the hardcoded path before merging.
