### PR TITLE
Redesign IBC on packet recv error/ result.Err handling

### LINKED ISSUE #1220: Let contract fully abort IBC receive in certain case
### Placeholder

To be refined better by @ethanfrey 

### Background
In IBC-go:
`OnRecvPacket` returns an Ack object that can either indicate success or failure of the operation. State is only persisted for the success case. 
Returning `nil` would persist state but not store the Acknowledgment.
The forth case is `panic` which would not persist state nor store an Ack.

```go
	cacheCtx, writeFn = ctx.CacheContext()
	ack := cbs.OnRecvPacket(cacheCtx, msg.Packet, relayer)
	if ack == nil || ack.Success() {
		// write application state changes for asynchronous and successful acknowledgements
		writeFn()
	} else {
		// NOTE: The context returned by CacheContext() refers to a new EventManager, so it needs to explicitly set events to the original context.
		// Events should still be emitted from failed acks and asynchronous acks
		ctx.EventManager().EmitEvents(cacheCtx.EventManager().Events())
	}

	// Set packet acknowledgement only if the acknowledgement is not nil.
	// NOTE: IBC applications modules may call the WriteAcknowledgement asynchronously if the
	// acknowledgement is nil.
	if ack != nil {
		if err := k.ChannelKeeper.WriteAcknowledgement(ctx, cap, msg.Packet, ack); err != nil {
			return nil, err
		}
	}
```
in `modules/core/keeper/msg_server.go`

### LINKED ISSUE #1288: Emit event for ibc error returned
The json returned for contract errors on IBC package receive is redacted: 
```json
{"error":"ABCI code: 5: error handling packet: see events for details"}`
```

> It is the responsibility of the application developer to emit error details in events.

https://github.com/cosmos/ibc-go/pull/1565/files#diff-c84c5415c1edd86b6332b4c8e95c325d4551550993fafc997bf9453a81f1b192R31

## Update: 
With the work in #1220  and #1289  there should not be any need for emitting the original error message as event. The contract's error string is included in the error Ack.
But this is not the case for sub-messages that fail. See https://github.com/cosmos/ibc-go/blob/v7.0.0/modules/apps/transfer/ibc_module.go#L202 for an example event

In [ibc-go](https://github.com/cosmos/ibc-go/blob/v7.0.0/modules/core/keeper/msg_server.go#L459) all events are emitted on error Ack as well. This is a different behaviour than we have with other contract calls.
There are 2 cases to consider:
1) the contract returns an error Ack and events
2) the contract returns a success Ack but any of the sub-messages returned fails

As a simple solution, we can drop all events on error Ack in wasm/ibc.go
Or we always accept contract events but drop sub-message events on error in keeper/relay.go.

### LINKED ISSUE #1289: Return non redacted error content on IBC packet recv
Current response in json is: `{"error":"ABCI code: 5: error handling packet: see events for details"}`
Instead of the default error constructor, we could pass the string directly

Note: Only for this case: https://github.com/CosmWasm/wasmd/blob/v0.31.0/x/wasm/keeper/relay.go#L135-L136

See also #1220

### PR DESCRIPTION
**Pull request by alpe**
Resolved when backported:
* See #1289 
* See #1288 
* See #1220

Based on design spike #1299

See this very nice document for a detailed description: https://github.com/CosmWasm/cosmwasm/blob/ibc_packet_receive-erros/docs/ERROR_HANDLING.md#handing-ibc_packet_receive-errors for

### CODE REVIEW

File: x/wasm/ibc_test.go [hunk 1]
```diff
@@ -4,11 +4,125 @@ import (
...
 	channeltypes "github.com/cosmos/ibc-go/v7/modules/core/04-channel/types"
+	ibcexported "github.com/cosmos/ibc-go/v7/modules/core/exported"
 	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+
+	"github.com/CosmWasm/wasmd/x/wasm/keeper"
+	"github.com/CosmWasm/wasmd/x/wasm/types"
 )
 
+func TestOnRecvPacket(t *testing.T) {
```
Comment (pinosu) [inline x/wasm/ibc_test.go:21]: Very good tests! 👍

**Review by pinosu — APPROVED** [review]
Good work! 👍

**Comment by alpe** [comment]
This is the last PR missing for a new RC on the 47 branch. 
I will merge and tag now to unblock people. I would still appreciate feedback from you @webmaster128 . Let's use the backport branch for comments. Any changes will still go into main.
