### PR TITLE
Ensure query isolation

### LINKED ISSUE #610: Ensure Queries are executed read only
We could fail on any write operation or discard any changes as the SDK does.

### PR DESCRIPTION
**Pull request by alpe**
Resolves #610

### CODE REVIEW

File: x/wasm/keeper/query_plugins.go [hunk 1]
```diff
@@ -46,15 +46,15 @@ type GRPCQueryRouter interface {
 var _ wasmvmtypes.Querier = QueryHandler{}
 
 func (q QueryHandler) Query(request wasmvmtypes.QueryRequest, gasLimit uint64) ([]byte, error) {
-	// set a limit for a subctx
+	// set a limit for a subCtx
 	sdkGas := q.gasRegister.FromWasmVMGas(gasLimit)
-	subctx := q.Ctx.WithGasMeter(sdk.NewGasMeter(sdkGas))
+	subCtx, _ := q.Ctx.WithGasMeter(sdk.NewGasMeter(sdkGas)).CacheContext()
```
Comment (ethanfrey) [inline x/wasm/keeper/query_plugins.go:51]: This means all writes will be silently ignores, right?
That should be documented, but seems safe enough.

File: x/wasm/keeper/keeper_test.go [hunk 2]
```diff
@@ -1652,6 +1652,37 @@ func TestReply(t *testing.T) {
 	}
 }
 
+func TestQueryIsolation(t *testing.T) {
```
Comment (ethanfrey) [inline x/wasm/keeper/keeper_test.go:1655]: Nice test

**Review by ethanfrey — APPROVED** [review]
Very nice, clean, minimal change providing an important safety guarantee.
I like it.
