### PR TITLE
Genesis code import not position agnostic

### LINKED ISSUE #166: Genesis: code import should be more resilient
## Summary

The position of a code_info within the code block matters for the codeID generation during import. 

## Problem Definition
Switching two elements can therefore lead to different codeIDs and may cause contracts to point to the wrong one. This should be more resilient to manual edits.

## Proposal

We should not rely on the order but have the codeID defined explicitly.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by alpe**
Resolves #166 

The codeID is stored within the genesis data so that the order in the file does not matter anymore.

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: x/wasm/internal/keeper/genesis.go [hunk 1]
```diff
@@ -48,11 +56,15 @@ func ExportGenesis(ctx sdk.Context, keeper Keeper) types.GenesisState {
 
 	maxCodeID := keeper.GetNextCodeID(ctx)
 	for i := uint64(1); i < maxCodeID; i++ {
+		if !keeper.containsCodeInfo(ctx, i) {
```
Comment (ethanfrey) [inline x/wasm/internal/keeper/genesis.go:59]: okay, see how this can be slow if there are *huge* gaps. But this is export and only if someone decides to play around at genesis time
