### PR TITLE
Fix home dir issue in export command

### LINKED ISSUE #334: Invalid homeDir for export command
The wasmd doesn't pass the homeDir properly when using export command.
It passes always `wasm` as the homeDir.

**Step to reproduce**
```
wasmd export

                                                                          1 ↵
panic: Error calling the VM: Cache error: Error opening Wasm file for reading: No such file or directory (os error 2)

goroutine 1 [running]:
github.com/CosmWasm/wasmd/x/wasm/internal/keeper.ExportGenesis.func1(0x1, 0xc000fc5a80, 0x20, 0x20, 0xc000f6b950, 0x2b, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/CosmWasm/wasmd/x/wasm/internal/keeper/genesis.go:67 +0x2b4
github.com/CosmWasm/wasmd/x/wasm/internal/keeper.Keeper.IterateCodeInfos(0x5bc7de0, 0xc001068210, 0x5c00260, 0xc000c80470, 0x5bc7de0, 0xc001068140, 0x5bf9c40, 0xc000c80470, 0x5bf9c40, 0xc000c80470, ...)
	github.com/CosmWasm/wasmd/x/wasm/internal/keeper/keeper.go:574 +0x287
github.com/CosmWasm/wasmd/x/wasm/internal/keeper.ExportGenesis(0x5be7be0, 0xc0000c8030, 0x5bfd860, 0xc0010809c0, 0x0, 0x0, 0x0, 0x0, 0x116, 0x0, ...)
```

debugging

### PR DESCRIPTION
**Pull request by alpe**
Resolves #334 

Manually tested with a local instance and `wasmd export` and ``wasmd --home=/<non-default-dir> export`

### CODE REVIEW

File: cmd/wasmd/root.go [hunk 1]
```diff
@@ -237,19 +238,23 @@ func newApp(logger log.Logger, db dbm.DB, traceStore io.Writer, appOpts serverty
...
 
-func createWasnAppAndExport(
+func createWasmAppAndExport(
 	logger log.Logger, db dbm.DB, traceStore io.Writer, height int64, forZeroHeight bool, jailAllowedAddrs []string,
 	appOpts servertypes.AppOptions) (servertypes.ExportedApp, error) {
 
 	var wasmApp *app.WasmApp
+	homePath, ok := appOpts.Get(flags.FlagHome).(string)
+	if !ok || homePath == "" {
+		return servertypes.ExportedApp{}, errors.New("application home not set")
```
Comment (ethanfrey) [inline cmd/wasmd/root.go:248]: nice one

File: cmd/wasmd/root.go [hunk 2]
```diff
@@ -237,19 +238,23 @@ func newApp(logger log.Logger, db dbm.DB, traceStore io.Writer, appOpts serverty
...
+	}
 	if height != -1 {
-		wasmApp = app.NewWasmApp(logger, db, traceStore, false, map[int64]bool{}, "", uint(1), app.GetEnabledProposals(), appOpts)
+		wasmApp = app.NewWasmApp(logger, db, traceStore, false, map[int64]bool{}, homePath, uint(1), app.GetEnabledProposals(), appOpts)
```
Comment (ethanfrey) [inline cmd/wasmd/root.go:251]: wow, we literally just passed `""` in there. surprised other code worked.

**Review by ethanfrey — APPROVED** [review]
ack
