### PR TITLE
Fix param usage issue in genesis import

### LINKED ISSUE #335: Errors in `InitGenesis`
There exist errors in `InitGenesis` of the latest code.

1. Using params before they are initialized.
   - https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/keeper/genesis.go#L17
      - https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/keeper/keeper.go#L166
         - https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/keeper/keeper.go#L117
   - This will cause a nil error.

2. The `LastCodeID` is always zero after importing codes
   - In `importCode`, It inserts codes but does not increase lastCodeId
   - So It always steps into the error case from the below code.
      - https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/keeper/genesis.go#L47-L49

### PR DESCRIPTION
**Pull request by alpe**
Resolves #335  (first point only)

The genesis test setup was modified in `setupKeeper ` to not have params set there. The reported issue was confirmed by the tests then.

### CODE REVIEW

File: x/wasm/internal/keeper/genesis_test.go [hunk 1]
```diff
@@ -482,12 +482,11 @@ func TestImportContractWithCodeHistoryReset(t *testing.T) {
...
 }
 
-func setupKeeper(t *testing.T) (*Keeper, sdk.Context, []sdk.StoreKey, func()) {
+func setupKeeper(t *testing.T) (*Keeper, sdk.Context, []sdk.StoreKey) {
 	t.Helper()
 	tempDir, err := ioutil.TempDir("", "wasm")
 	require.NoError(t, err)
-	cleanup := func() { os.RemoveAll(tempDir) }
-	//t.Cleanup(cleanup) todo: add with Go 1.14
+	t.Cleanup(func() { os.RemoveAll(tempDir) })
```
Comment (ethanfrey) [inline x/wasm/internal/keeper/genesis_test.go:489]: Such a nice trick, cleaning up a lot

File: x/wasm/internal/keeper/genesis.go [hunk 2]
```diff
@@ -12,6 +12,8 @@ import (
 //
 // CONTRACT: all types of accounts must have been already initialized/created
 func InitGenesis(ctx sdk.Context, keeper *Keeper, data types.GenesisState) error {
+	keeper.setParams(ctx, data.Params)
```
Comment (ethanfrey) [inline x/wasm/internal/keeper/genesis.go:15]: Much better

**Review by ethanfrey — APPROVED** [review]
ack
