### PR TITLE
Fix query handler instantiation

### LINKED ISSUE #604: Fix bug in query handler initialization on reply
🙅 https://github.com/CosmWasm/wasmd/blob/v0.18.0/x/wasm/keeper/keeper.go#L486-L489

### PR DESCRIPTION
**Pull request by alpe**
Fixes #604

### CODE REVIEW

File: x/wasm/keeper/keeper_test.go [hunk 1]
```diff
@@ -1591,28 +1591,54 @@ func TestReply(t *testing.T) {
...
-			rsp:     wasmvmtypes.Response{Data: []byte("foo")},
+			replyFn: func(codeID wasmvm.Checksum, env wasmvmtypes.Env, reply wasmvmtypes.Reply, store wasmvm.KVStore, goapi wasmvm.GoAPI, querier wasmvm.Querier, gasMeter wasmvm.GasMeter, gasLimit uint64, deserCost wasmvmtypes.UFraction) (*wasmvmtypes.Response, uint64, error) {
+				return &wasmvmtypes.Response{Data: []byte("foo")}, 1, nil
+			},
+			expData: []byte("foo"),
+			expEvt:  sdk.Events{sdk.NewEvent("reply", sdk.NewAttribute("_contract_address", example.Contract.String()))},
+		},
+		"with query": {
+			replyFn: func(codeID wasmvm.Checksum, env wasmvmtypes.Env, reply wasmvmtypes.Reply, store wasmvm.KVStore, goapi wasmvm.GoAPI, querier wasmvm.Querier, gasMeter wasmvm.GasMeter, gasLimit uint64, deserCost wasmvmtypes.UFraction) (*wasmvmtypes.Response, uint64, error) {
+				bzRsp, err := querier.Query(wasmvmtypes.QueryRequest{
```
Comment (ethanfrey) [inline x/wasm/keeper/keeper_test.go:1608]: good test

File: x/wasm/keeper/keeper_test.go [hunk 2]
```diff
@@ -1591,28 +1591,54 @@ func TestReply(t *testing.T) {
...
+				require.NoError(t, json.Unmarshal(bzRsp, &gotBankRsp))
+				assert.Equal(t, wasmvmtypes.BalanceResponse{Amount: wasmvmtypes.NewCoin(0, "stake")}, gotBankRsp)
+				return &wasmvmtypes.Response{Data: []byte("foo")}, 1, nil
+			},
+			expData: []byte("foo"),
+			expEvt:  sdk.Events{sdk.NewEvent("reply", sdk.NewAttribute("_contract_address", example.Contract.String()))},
+		},
+		"with query error handled": {
+			replyFn: func(codeID wasmvm.Checksum, env wasmvmtypes.Env, reply wasmvmtypes.Reply, store wasmvm.KVStore, goapi wasmvm.GoAPI, querier wasmvm.Querier, gasMeter wasmvm.GasMeter, gasLimit uint64, deserCost wasmvmtypes.UFraction) (*wasmvmtypes.Response, uint64, error) {
+				bzRsp, err := querier.Query(wasmvmtypes.QueryRequest{}, 0)
```
Comment (ethanfrey) [inline x/wasm/keeper/keeper_test.go:1624]: and nice to cover error case as well

**Review by ethanfrey — APPROVED** [review]
lgtm. important fix
